tasks:
- install:
- ceph:
- openssl_keys:
- rgw:
    ec-pools: true
    client.0:

overrides:
  install:
    ceph:
      extra_system_packages:
        rpm:
        - java
        deb:
        - default-jre
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
