overrides:
  ceph:
    cephfs:
      ec_metadata_profile:
        - m=2
        - k=2
        - crush-failure-domain=osd
      ec_profile:
        - disabled
    conf:
      client:
        client_fscrypt_dummy_encryption: true
  ceph-fuse:
